### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by HonzaMac** [pascaldevink/intellij-thesaurus#2]
Hi, please, provide me info, how could i get these suggestions from thesaurus? 
What is the trigger?
I could not find any special action cmd + shift + A.
PHPstorm 9.5

thanks

**Comment by pascaldevink** [comment]
Hi, I've updated both the README.md in this repository, as well as the description of the plugin.
I hope it's more clear now how to use it.

If you have any suggestions in how it can be used, please open another issue (or submit it as a pull request :) )
